using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;

namespace Telemetry.Viewer.Views.Worksheet;

// Hosts the worksheet's ItemsControl. Code-behind is intentionally minimal:
// it forwards "click on the empty canvas" to the bound Worksheet so it can
// place a pending plot (or clear selection). Cursor follows the worksheet's
// IsArmed flag.
public partial class WorksheetGrid : UserControl
{
    public WorksheetGrid()
    {
        InitializeComponent();
        DataContextChanged += OnDataContextChanged;
    }

    private Worksheet? _worksheet;

    private void OnDataContextChanged(object sender, DependencyPropertyChangedEventArgs e)
    {
        if (_worksheet is not null)
            _worksheet.Placement.PropertyChanged -= OnPlacementChanged;
        _worksheet = e.NewValue as Worksheet;
        if (_worksheet is not null)
            _worksheet.Placement.PropertyChanged += OnPlacementChanged;
    }

    private void OnPlacementChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
        if (e.PropertyName != nameof(PlotPlacementController.IsArmed)) return;
        Cursor = _worksheet?.Placement.IsArmed == true ? Cursors.Cross : null;
    }

    // Empty-canvas click only — clicks on a PlotItemHost mark the event handled
    // upstream. We use Preview to detect them BEFORE they're handled.
    private void OnCanvasPreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
    {
        if (_worksheet is null) return;

        // Walk up from the click target: if any ancestor is a PlotItemHost,
        // the click is on a plot, not the empty canvas — selection/drag will
        // handle it.
        if (e.OriginalSource is DependencyObject obj && AncestorIsPlotHost(obj))
            return;

        var canvas = FindCanvas(this);
        if (canvas is null) return;

        var pos = e.GetPosition(canvas);
        _worksheet.OnCanvasClick(pos);
        e.Handled = true;
    }

    private static bool AncestorIsPlotHost(DependencyObject obj)
    {
        while (obj is not null)
        {
            if (obj is PlotItemHost) return true;
            obj = VisualTreeHelper.GetParent(obj) ?? LogicalTreeHelper.GetParent(obj);
        }
        return false;
    }

    // The Canvas inside the ItemsPanel is generated by the ItemsControl —
    // walk down the tree to find it.
    private static Canvas? FindCanvas(DependencyObject root)
    {
        for (int i = 0; i < VisualTreeHelper.GetChildrenCount(root); i++)
        {
            var child = VisualTreeHelper.GetChild(root, i);
            if (child is Canvas c) return c;
            var deeper = FindCanvas(child);
            if (deeper is not null) return deeper;
        }
        return null;
    }
}
